version: "3.9"
services: 
    api:
        image: nefcanto/dotnet-dev:latest
        restart: always
        container_name: Tickting
        working_dir: /Tickting
        environment: 
            - HolismProjectsRoot=/HolismDotNet
        volumes: 
             - .:/Tickting
        ports: 
            - "5000:5000"
        command: >
            sh -c
            "
            tail -f /dev/null           
            " 